/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
  'clearChat' : IDL.Func([IDL.Text], [], []),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'setPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
    'clearChat' : IDL.Func([IDL.Text], [], []),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'setPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };